Added All_Notes_Off command when switching off Midi notes to Fluid to avoid hanging notes.

diff --git a/Scripts/GuitarEffects b/Scripts/GuitarEffects
--- a/Scripts/GuitarEffects
+++ b/Scripts/GuitarEffects
@@ -331,8 +331,14 @@ function FindDevice {
     echo $DeviceList | grep "${Device}"
     if [ "$?" -eq 0 ]; then
         echo "We have " $Device >> $LogFile
-        AudioSampleRate=48000
-        # AudioSampleRate=96000
+        # AudioSampleRate=48000
+        # JBuffer=64
+        # JPeriod=3
+ 
+        AudioSampleRate=96000
+        JBuffer=128
+        JPeriod=2
+
         #       AudioSampleRate=192000
         AudioDevice="$Device"
         AudioInDevice="$Device"
@@ -614,6 +620,11 @@ function SetUpConnections {
     jack_connect gx_head_fx:out_1 $MainOut1
     jack_disconnect gx_head_fx:out_1 system:playback_1
     jack_disconnect gx_head_fx:out_0 system:playback_2
+
+#    jack_connect gx_head_fx:out_0 loud_comp_mono:in
+#    jack_connect gx_head_fx:out_1 loud_comp_mono:in
+#    jack_connect loud_comp_mono:out $MainOut1
+
     
     # Connect Guitarix out to looper in
     jack_connect gx_head_fx:out_1 sooperlooper:common_in_1
@@ -814,6 +825,9 @@ function SetPlacement {
     #   ExtID=`xinput list | grep -Po 'ILITEK.*id=\K[0-9]+'`
     #   xinput map-to-output $ExtID HDMI1
     
+    xrandr | grep "HDMI1 connected"
+    ExtraMonitor="$?"
+
     # On home PC spread it out
     if [ `hostname` == "Keshie" ]; then
         echo "Keshie"
@@ -827,6 +841,13 @@ function SetPlacement {
         YOffset=1080
         YOffset=900
         
+#        if [ "$?" -eq "1" ]
+        
+        if [ "$ExtraMonitor" -eq "1" ]; then
+            YOffset=0
+            echo "External Monitor Not Found"
+        fi
+
         SetPlacement1920
     elif [ `hostname` == "Music" ]; then
         echo "Music"
@@ -1429,5 +1450,9 @@ exit 0
 # /home/elias/.config/guitarix/gx_head_rc
 #
 # lsp-plugins-loud-comp-mono -c /home/elias/LoudCompensation.cfg
+#loud_comp_mono:in
+#loud_comp_mono:out
+
+
 # GDK_BACKEND=broadway BROADWAY_DISPLAY=:5 gtk3-demo
 
